# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}

name: Build Go

on:
#  push:
#    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Docker-image-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build frontend
        run: chmod +x ci/build-frontend.sh && ci/build-frontend.sh

      - name: push docker frontend
        run: chmod +x ci/push-docker-frontend.sh && ci/push-docker-frontend.sh
  
  Docker-image-backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build backend
        run: chmod +x ci/build-backend.sh && ci/build-backend.sh

      - name: push docker backend
        run: chmod +x ci/push-docker-backend.sh && ci/push-docker-backend.sh

  deploy:

    runs-on: ubuntu-latest
    needs: [Docker-image-frontend, Docker-image-backend]

    steps:
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - run: kubectl --kubeconfig kubeconfig get pods
