name: 03_automation
on:
   push
    #pull_request:
   #   branches: 
    #     - main 
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cd frontend/ && go test
  #  - name: kubefonfig1
  #    run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
  #  - name: kubefonfig2
  #    run: kubectl --kubeconfig kubeconfig <your kubectl commands>
